# Site settings
title: WinterHouse
description: "A minimal blog "
url: "http://695215742.github.io/"
author:
  name: "WinterHouse"
  url: "http://695215742.github.io/"

# Build settings
baseurl: http://695215742.github.io/
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
