auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: WinterHouse.com
url: http://695215742.github.io/
feed: /atom.xml
author_info: <a href="http://695215742.github.io/">WinterHouse</a>
